/*!40101 SET NAMES utf8 */;

CREATE TABLE uvotes (
  id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  votingip VARCHAR(30) NOT NULL,
  points INT(10) UNSIGNED,
  last_vote TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET=utf8;
