CREATE TABLE IF NOT EXISTS uvotes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(20) NOT NULL,
  votingip VARCHAR(30) NOT NULL,
  points INTEGER,
  last_vote TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
